# Import libraries

In [1]:
import os
import warnings

import numpy as np
import pandas as pd

In [2]:
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', 50)

In [3]:
path_to_save_data = './../data/preprocessed_data'
path_to_save = './../results/01_visualization'

# Loading & parsing data

In [4]:
path_to_ftir = './../data/raw_data'

*Collecting paths to subfolders in `path_to_ftir`*

In [5]:
division_folders = []

subfolder_names_lst = os.listdir(path_to_ftir)

for subfolder in subfolder_names_lst:
    isdir_flg = os.path.isdir(os.path.join(path_to_ftir, subfolder))
    startswith_division_flg = subfolder.startswith("division_")
    
    if isdir_flg and startswith_division_flg:
        path_to_subfolder = os.path.join(path_to_ftir, subfolder)
        division_folders.append(path_to_subfolder)

*Collecting paths to all file and sorting them*

In [6]:
files = []

for folder in division_folders:
    for filename in os.listdir(folder):
        file_path = os.path.join(folder, filename)
        
        if os.path.isfile(file_path) and filename.endswith(".dpt"):
            files.append(file_path)

In [7]:
files = sorted(
    files,
    key=lambda x: (
        os.path.basename(x).split("_")[0].replace(".", "").isnumeric(),
        float(os.path.basename(x).split("_")[0]) if os.path.basename(x).split("_")[0].replace(".", "").isnumeric() else os.path.basename(x)
    ),
    reverse=True
)

*Reading all files*

In [8]:
spectra_dict = {}
description_dict = {}

for i, file_path in enumerate(files):
    filename = os.path.basename(file_path)
    folder_name = os.path.basename(os.path.dirname(file_path))
    fraction_name = filename.split("_")[0]

    try:
        tmp_df = pd.read_csv(file_path, sep=",", header=None)
        wavenumbers = tmp_df[0].values
        intensities = tmp_df[1].values

        key = f"{folder_name}_size_{fraction_name}"
        
        spectra_dict[key] = intensities
        description_dict[key] = [i+1, folder_name.split('_')[-1], fraction_name]

    except Exception as e:
        print(f"Ошибка при чтении {file_path}: {e}")

## Spectral data

In [9]:
initial_data = pd.DataFrame.from_dict(
    spectra_dict,
    orient="index",
    columns=wavenumbers
)

initial_data = initial_data.sort_index(
    key=lambda x: x.map(lambda y: (float(y.split('_')[1]), -float(y.split('_')[-1].replace('bulk', '1000')))),
    ascending=True
)

print(initial_data.shape)
initial_data.head(3)

(61, 3733)

,3998.31069,3997.34631,3996.38194,3995.41756,3994.45318,3993.48880,3992.52442,3991.56005,3990.59567,3989.63129,3988.66691,3987.70253,3986.73816,3985.77378,3984.80940,3983.84502,3982.88065,3981.91627,3980.95189,3979.98751,3979.02313,3978.05876,3977.09438,3976.13000,3975.16562,...,422.39751,421.43313,420.46876,419.50438,418.54000,417.57562,416.61124,415.64687,414.68249,413.71811,412.75373,411.78935,410.82498,409.86060,408.89622,407.93184,406.96747,406.00309,405.03871,404.07433,403.10995,402.14558,401.18120,400.21682,399.25244
division_1_size_bulk,-0.008580,-0.008580,-0.008580,-0.008580,-0.008580,-0.008580,-0.008580,-0.008612,-0.008578,-0.008559,-0.008554,-0.008587,-0.008574,-0.008486,-0.008457,-0.008504,-0.008556,-0.008586,-0.008602,-0.008547,-0.008460,-0.008443,-0.008471,-0.008505,-0.008509,...,0.005667,0.005664,0.005700,0.005717,0.005726,0.005732,0.005741,0.005662,0.005531,0.005438,0.005388,0.005372,0.005361,0.005383,0.005366,0.005290,0.005246,0.005210,0.005174,0.005174,0.005174,0.005174,0.005174,0.005174,0.005174
division_1_size_5,-0.008005,-0.008005,-0.008005,-0.008005,-0.008005,-0.008005,-0.008005,-0.008121,-0.008191,-0.008250,-0.008269,-0.008278,-0.008247,-0.008157,-0.008120,-0.008136,-0.008145,-0.008111,-0.008079,-0.008044,-0.007976,-0.007943,-0.007927,-0.007923,-0.007929,...,0.010026,0.010000,0.009974,0.009935,0.009883,0.009873,0.009853,0.009706,0.009551,0.009473,0.009416,0.009341,0.009259,0.009198,0.009123,0.009064,0.009072,0.009097,0.009078,0.009078,0.009078,0.009078,0.009078,0.009078,0.009078
division_1_size_3,-0.003743,-0.003743,-0.003743,-0.003743,-0.003743,-0.003743,-0.003743,-0.003775,-0.003766,-0.003757,-0.003773,-0.003883,-0.003973,-0.003965,-0.003945,-0.003949,-0.003970,-0.003917,-0.003853,-0.003797,-0.003700,-0.003678,-0.003729,-0.003794,-0.003794,...,0.005184,0.005200,0.005233,0.005221,0.005201,0.005209,0.005200,0.005069,0.004923,0.004889,0.004884,0.004844,0.004761,0.004684,0.004632,0.004606,0.004621,0.004636,0.004621,0.004621,0.004621,0.004621,0.004621,0.004621,0.004621

## Samples description

In [10]:
samples_description = pd.DataFrame.from_dict(
    description_dict,
    orient='index',
    columns=['Row_ID', 'Division', 'Size']
)

samples_description = samples_description.sort_index(
    key=lambda x: x.map(lambda y: (float(y.split('_')[1]), -float(y.split('_')[-1].replace('bulk', '1000')))),
    ascending=True
)
print(samples_description.shape)
samples_description.head(3)

(61, 3)

                      Row_ID Division  Size
division_1_size_bulk      58        1  bulk
division_1_size_5         18        1     5
division_1_size_3         27        1     3

In [11]:
samples_description['Fraction_hue'] = (
    samples_description['Size']
    .apply(
        lambda x:
           f'$> 0$' if x.split('_')[-1] == 'bulk'
           else f'$< {x.split("_")[-1]}$'
    )
)

print(samples_description.shape)
samples_description.head(3)

(61, 4)

                      Row_ID Division  Size Fraction_hue
division_1_size_bulk      58        1  bulk        $> 0$
division_1_size_5         18        1     5        $< 5$
division_1_size_3         27        1     3        $< 3$

In [12]:
samples_description['Fraction_grouped_hue'] = (
    samples_description['Size']
    .apply(
        lambda x:
            rf'$0< d \leq 2$' if float(x.replace('bulk', '1000')) <= 2.0
            else rf'$2 < d \leq 5$' if float(x.replace('bulk', '1000')) <= 5.0
            else rf'$d > 5$'
    )
)

print(samples_description.shape)
samples_description.head(3)

(61, 5)

                      Row_ID Division  Size Fraction_hue Fraction_grouped_hue
division_1_size_bulk      58        1  bulk        $> 0$              $d > 5$
division_1_size_5         18        1     5        $< 5$       $2 < d \leq 5$
division_1_size_3         27        1     3        $< 3$       $2 < d \leq 5$

In [13]:
samples_description['Row_ID'] = range(1, samples_description.shape[0]+1)

print(samples_description.shape)
samples_description.head(3)

(61, 5)

                      Row_ID Division  Size Fraction_hue Fraction_grouped_hue
division_1_size_bulk       1        1  bulk        $> 0$              $d > 5$
division_1_size_5          2        1     5        $< 5$       $2 < d \leq 5$
division_1_size_3          3        1     3        $< 3$       $2 < d \leq 5$

# Saving data

In [14]:
path_to_save = './../data/parsed_data'

In [15]:
initial_data.to_csv(f'{path_to_save}/ftir_raw_spectra.csv', sep=';')
samples_description.to_csv(f'{path_to_save}/samples_description.csv', sep=';')